baseURL = 'https://alphacjmav.github.io/calculadora3D/'
googleAnalytics = ""
theme = "PaperMod"
publishDir = "docs"
languageCode = 'es'
title = "Alpha Impresiones 3D"
defaultContentLanguage = "es"
enableRobotsTXT = true
canonifyURLs = true

[params]
  homeInfoParams = { Title = "3D Alpha Impresiones", Content = "Calcul치 tus precios de impresi칩n f치cilmente y mucho m치s" }
  ShowReadingTime = false
  ShowShareButtons = false
  ShowCodeCopyButtons = true
  themeColor = "light"
  customCSS = ["css/custom.css"]

[markup.goldmark.renderer]
  unsafe = true  # permite HTML incrustado

[[menu.main]]
  name = "Inicio"
  url = "/"
  weight = 1

  [params.assets]
    disableFingerprinting = true
