baseURL = 'https://alphacjmav.github.io/calculadora3D/'
googleAnalytics = ""
theme = "PaperMod"
publishDir = "docs"
languageCode = 'es'
title = 'Calculadora 3D Alpha Impresiones'
defaultContentLanguage = "es"
enableRobotsTXT = true
canonifyURLs = true

[params]
  ShowReadingTime = false
  ShowShareButtons = false
  ShowCodeCopyButtons = true
  themeColor = "light"
  homeInfoParams = { Title = "Calculadora 3D Alpha Impresiones", Content = "Calculá tus precios de impresión fácilmente" }

[markup.goldmark.renderer]
  unsafe = true  # permite HTML incrustado

[[menu.main]]
  name = "Inicio"
  url = "/"
  weight = 1
